name: Deploy Polybot to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        echo "${{ secrets.SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Copy code and install dependencies
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.USER }}@${{ secrets.HOST }} '
          sudo apt update
          sudo apt install -y git python3-pip python3-venv
          rm -rf PlaybotHojere
          git clone https://github.com/${{ github.repository }} PlaybotHojere
          cd PlaybotHojere/polybot
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        '

    - name: Upload and enable systemd service
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.USER }}@${{ secrets.HOST }} "bash -s" <<'EOF'
          SERVICE_FILE="/etc/systemd/system/mypolybot.service"
          sudo sh -c "echo '[Unit]' > \$SERVICE_FILE"
          sudo sh -c "echo 'Description=Telegram PolyBot' >> \$SERVICE_FILE"
          sudo sh -c "echo 'After=network.target' >> \$SERVICE_FILE"

          sudo sh -c "echo '' >> \$SERVICE_FILE"
          sudo sh -c "echo '[Service]' >> \$SERVICE_FILE"
          sudo sh -c "echo 'WorkingDirectory=/home/${{ secrets.USER }}/PlaybotHojere/polybot' >> \$SERVICE_FILE"
          sudo sh -c \"echo 'ExecStart=/home/${{ secrets.USER }}/PlaybotHojere/polybot/venv/bin/python3 /home/${{ secrets.USER }}/PlaybotHojere/polybot/app.py' >> \$SERVICE_FILE\"
          sudo sh -c \"echo 'Environment=TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}' >> \$SERVICE_FILE\"
          sudo sh -c \"echo 'Environment=BOT_APP_URL=${{ secrets.BOT_APP_URL }}' >> \$SERVICE_FILE\"
          sudo sh -c "echo 'Restart=always' >> \$SERVICE_FILE"
          sudo sh -c "echo 'User=${{ secrets.USER }}' >> \$SERVICE_FILE"

          sudo sh -c "echo '' >> \$SERVICE_FILE"
          sudo sh -c "echo '[Install]' >> \$SERVICE_FILE"
          sudo sh -c "echo 'WantedBy=multi-user.target' >> \$SERVICE_FILE"

          sudo systemctl daemon-reexec
          sudo systemctl daemon-reload
          sudo systemctl enable mypolybot
          sudo systemctl restart mypolybot
EOF

